### ISSUE TITLE
Test with multiple steps fails to create

### ISSUE THREAD

**Issue by DavidSpek** [pluralsh/test-harness#4]
If there are multiple steps in a test it fails to create. The version before the new GraphQL client does not have this issue.

```console
1.659704515816125e+09	INFO	controllers.TestSuite	Creating new argo workflow for testsuite	{"testsuite": "console/console-integration-sxu6o"}
1.6597045159085405e+09	ERROR	controllers.TestSuite	failed to create plural test	{"testsuite": "console/console-integration-sxu6o", "error": "the Test response is nil"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227
1.6597045159086432e+09	ERROR	controller.testsuite	Reconciler error	{"reconciler group": "test.plural.sh", "reconciler kind": "TestSuite", "name": "console-integration-sxu6o", "namespace": "console", "error": "the Test response is nil"}
```

example spec:

```yaml
spec:
  promoteTag: warm
  repository: console
  steps:
    - description: it wait until the console app crd is ready
      name: watch
      template:
        container:
          args:
            - console
          image: gcr.io/pluralsh/test-base:0.1.6
    - description: it wait until the console app crd is ready
      name: watch
      template:
        container:
          args:
            - console
          image: gcr.io/pluralsh/test-base:0.1.6
```
